// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3NF.Decomposition.Persistance.Data;

namespace _3NF.Decomposition.Persistance.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RelationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelationId");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.FminAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RelationId")
                        .HasColumnType("int");

                    b.Property<int>("LeftSideAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("RightSideAttributeId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id", "RelationId", "LeftSideAttributeId", "RightSideAttributeId", "Sequence");

                    b.HasIndex("LeftSideAttributeId");

                    b.HasIndex("RelationId");

                    b.HasIndex("RightSideAttributeId");

                    b.ToTable("FminAttributes");
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RelationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelationId");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.KeyAttribute", b =>
                {
                    b.Property<int>("KeyId")
                        .HasColumnType("int");

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.HasKey("KeyId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("KeyAttributes");
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.Attribute", b =>
                {
                    b.HasOne("_3NF.Decomposition.Core.Entities.Relation", "Relation")
                        .WithMany("Attributes")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.FminAttribute", b =>
                {
                    b.HasOne("_3NF.Decomposition.Core.Entities.Attribute", "LeftSideAttribute")
                        .WithMany()
                        .HasForeignKey("LeftSideAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3NF.Decomposition.Core.Entities.Relation", "Relation")
                        .WithMany("FminAttributes")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3NF.Decomposition.Core.Entities.Attribute", "RightSideAttribute")
                        .WithMany()
                        .HasForeignKey("RightSideAttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.Key", b =>
                {
                    b.HasOne("_3NF.Decomposition.Core.Entities.Relation", "Relation")
                        .WithMany("Keys")
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_3NF.Decomposition.Core.Entities.KeyAttribute", b =>
                {
                    b.HasOne("_3NF.Decomposition.Core.Entities.Attribute", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_3NF.Decomposition.Core.Entities.Key", "Key")
                        .WithMany("KeyAttributes")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
